[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "backend"
path = "src/lib.rs"

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
lightyear = { version = "0.25.5", features = [
    "leafwing",
    "webtransport",
    "netcode",
    "udp",
] }
argon2 = "0.5.3"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
chrono = { version = "0.4.38", features = ["serde"] }
sqlx = { version = "0.8.2", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "uuid",
    "chrono",
] }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
shared = { path = "../crates/shared" }
chess_engine = { path = "../crates/chess_engine" }
rand = "0.9.2"
bevy = { version = "0.17.3", default-features = false, features = [
    "multi_threaded",
    "bevy_asset",
    "bevy_scene",
    "bevy_winit",
] }
dotenv = "0.15.0"
bincode = "1.3.3"
base64 = "0.22.1"
