[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.17"
futures-lite = "2.0"
instant = { version = "0.1", features = ["wasm-bindgen"] }

[features]
default = []
salewskiChessDebug = []

[lib]
name = "chess_engine"
path = "src/lib.rs"
